1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
b = np.arange(10,50)

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
c = np.random.randint(0,9, (3,3))

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [54]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

[array([ True,  True, False, False,  True, False])]


(array([0, 1, 4], dtype=int64),)

7. Create a 3x3 identity matrix (★☆☆)

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values (★☆☆)

In [28]:
np.random.random((3,3,3))

array([[[0.8171935 , 0.01391025, 0.03182773],
        [0.40407672, 0.63532782, 0.57002463],
        [0.99198007, 0.5937986 , 0.34289242]],

       [[0.80927896, 0.94963209, 0.29983777],
        [0.82295314, 0.14435986, 0.38933346],
        [0.83073301, 0.99172826, 0.0833269 ]],

       [[0.77083177, 0.91078808, 0.21435887],
        [0.19566981, 0.25181905, 0.05636968],
        [0.97323274, 0.5925954 , 0.09905526]]])

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
a = np.random.random((10,10))
print(np.max(a))
print(np.min(a))

0.999573109965585
0.011420555025561274


10. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
a = np.random.random(30)
a.mean()

0.5734646277972825

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [66]:
a = np.random.randint(0,1,(5,5))
lst = [1,2,3,4]
rows = 1
cols = 0
for i in lst:
    a[rows,cols] = i
    rows += 1
    cols += 1
print(a)
np.diag(lst,-1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix (★☆☆)

In [82]:
a = np.random.random((5,5))
print(a,"\n")

normalized = (a - np.mean(a)) / np.std(a) 
print(normalized)

[[0.96741906 0.09879718 0.91562597 0.55554032 0.2210385 ]
 [0.36443274 0.82661002 0.60670872 0.73689297 0.98733455]
 [0.01889782 0.97243189 0.23122699 0.43313237 0.84680191]
 [0.08527045 0.37437827 0.41698229 0.52389641 0.55312849]
 [0.80510794 0.50547856 0.14721953 0.36768208 0.60908342]] 

[[ 1.50521483 -1.46241735  1.3282646   0.09803799 -1.04478193]
 [-0.55487788  1.02414311  0.27285395  0.71762629  1.57325578]
 [-1.73539218  1.52234109 -1.00997313 -0.32016675  1.09312837]
 [-1.50863121 -0.52089916 -0.37534322 -0.01007292  0.089798  ]
 [ 0.95068159 -0.0729972  -1.29698319 -0.54377657  0.28096708]]


13. How to find common values between two arrays? (★☆☆)

In [89]:
a = np.random.random(5)
b = np.random.random(5)
print(a,b)
np.intersect1d(a,b)

[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119] [0.61174386 0.76590786 0.51841799 0.2968005  0.18772123]


array([], dtype=float64)

14. Create a random vector of size 10 and sort it (★★☆)

In [92]:
a = np.random.random(10)
np.sort(a)

array([0.00164217, 0.02293309, 0.02430656, 0.20455555, 0.51547261,
       0.57766286, 0.63979518, 0.69984361, 0.77951459, 0.9856244 ])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [121]:
a = np.random.random(10)
print(a)
print(np.argmax(a))

[0.92565181 0.96136808 0.00660811 0.43293059 0.58311263 0.34882757
 0.37603202 0.35582158 0.23103288 0.02603724]
1


16. Subtract the mean of each row of a matrix (★★☆)

In [162]:
np.random.seed(100)
a = np.random.random((2,2))
print(a,"\n")
mean = np.mean(a, axis=0, keepdims=0)
print(mean,"\n")
a - mean

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]] 

[0.48396127 0.56157276] 



array([[ 0.05944368, -0.28320337],
       [-0.05944368,  0.28320337]])

17. How to get the n largest values of an array (★★★)

In [137]:
a = np.random.random((10))
n = 2
np.argsort(a)[0:n]

array([5, 6], dtype=int64)

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

In [147]:
a = np.random.random((5,3))
np.where(a>4,a**2,a)

array([[0.23701044, 0.70000041, 0.416806  ],
       [0.89806363, 0.29788513, 0.54077708],
       [0.28499456, 0.94857772, 0.27776783],
       [0.67623853, 0.35436536, 0.68348972],
       [0.61987831, 0.77299252, 0.62625073]])